---

- name: Arch, install ntp
  pacman:
    name: ntp
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"


- name: Debian, install ntp
  apt:
    name: ntp
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"


- name: Ensure ntpd is started and enabled at boot.
  systemd:
    name: ntpd
    state: started
    enabled: yes
  when:
    - ansible_distribution in ["Archlinux","Debian"]
    - enable_ntpd_at_boot|default(true)


- name: Restart ntpd and reload systemd daemon
  systemd:
    name: ntpd
    state: restarted
    daemon_reload: yes
  when:
    - ansible_distribution in ["Archlinux","Debian"]
    - start_ntpd_immediately|default(true)







