---


#
# The Ansible pacman module cannot handle packages which are aliases of 
# others. It fails because of the way it tests to see if the package is 
# already installed.
#
# Because in the base-devel group package there is pkg-config, and 
# pkgconf, which is an alias of pkg-config, if we name base-devel 
# specifically the pacman module will fail.
#
# So here we install everything individually and not pkg-config, which is an
# alias for pkgconf.
#
# https://github.com/ansible/ansible/issues/24110
#


- name: Arch, install members of base-devel individually
  pacman:
    name: autoconf,automake,binutils,bison,fakeroot,file,findutils,flex,gawk,gcc,gettext,grep,groff,gzip,libtool,m4,make,pacman,patch,pkgconf,sed,sudo,systemd,texinfo,util-linux,which,python2-pip,python-pip,git,intltool
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - devtools

- name: Debian, install development tools
  apt:
    name: build-essential,git,intltool
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
  tags:
    - devtools

