---

- name: import tasks from sound.yml
  import_tasks: sound.yml
  when:
    - not skip_sound
  tags:
    - sound

- name: import tasks from user.yml
  import_tasks: user.yml
  when:
    - not skip_user
  tags:
    - user

- name: import tasks from speechd.yml
  import_tasks: speechd.yml
  when:
    - not skip_speechd
  tags:
    - speechd

#
# emacs-nox is installed in emacs.yml but same tasks are imported
# in console.yml as a dependency of emacspeak
#

- name: import tasks from emacs.yml
  import_tasks: emacs.yml
  when:
    - not skip_emacs
  tags:
    - emacs

- name: import tasks from console.yml
  import_tasks: console.yml
  when:
    - not skip_console
  tags:
    - console


- name: Import tasks from orca.yml
  import_tasks: orca.yml
  tags:
    - orca

- name: Import tasks from switches.yml
  import_tasks: switches.yml
  tags:
    - orca

