---

- name: Include the devtools role
  include_role:
    name: devtools


- name: Arch, install package-query
  aur:
    name: package-query
    user: "{{ default_user }}"
    dir: /tmp
  when:
    - ansible_distribution == "Archlinux"


- name: Arch, install yaourt
  aur:
    name: yaourt
    user: "{{ default_user }}"
    dir: /tmp
  when:
    - ansible_distribution == "Archlinux"


