---


- name: Raspbian, Copy motd template to /etc/motd
  template:
    src: motd.raspbian.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == "Debian"

