---

- name: Arch, Install brltty-minimal dependencies
  pacman:
    name: icu,liblouis
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - brltty


- name: Arch, install brltty-minimal from the AUR
  aur:
    name: brltty-minimal
    user: "{{ default_user }}"
    dir: /tmp
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - brltty

- name: Debian, install brltty
  apt:
    name: brltty
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
  tags:
    - brltty




