---

- name: Debian/Ubuntu, include the nginx_light role
  include_role:
    name: nginx_light
  when:
    - ansible_distribution in ["Debian","Ubuntu"]

- name: Debian/Ubuntu, copy the modified nginx.conf
  copy:
    src: conf.d.nginx.conf
    dest: /etc/nginx/conf.d/nginx.conf
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution in ["Debian","Ubuntu"]

- name: Debian/Ubuntu, replace main nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution in ["Debian","Ubuntu"]

- name: Debian/Ubuntu, copy uwsgi.ini
  copy:
    src: uwsgi.ini
    dest: /etc/uwsgi/
  when:
    - ansible_distribution in ["Debian","Ubuntu"]
