---


- name: Install regolith-i3 dependencies pt1
  apt:
    name: [libev-dev,libstartup-notification0-dev,libxcb-xkb-dev,libxcb-xinerama0-dev,libxcb-randr0-dev]
    update_cache: yes
  when:
      - ansible_distribution in ["Debian","Ubuntu"]


- name: Install regolith-i3 dependencies pt2
  apt:
    name: [libxcb-shape0-dev,libxcb-util0-dev,libxcb-cursor-dev,libxcb-keysyms1-dev,libxcb-icccm4-dev]
    update_cache: yes
  when:
      - ansible_distribution in ["Debian","Ubuntu"]


- name: Install regolith-i3 dependencies pt3
  apt:
    name: [libxcb-xrm-dev,libxkbcommon-dev,libxkbcommon-x11-dev,libyajl-dev,libpcre3-dev,libcairo2-dev]
    update_cache: yes
  when:
      - ansible_distribution in ["Debian","Ubuntu"]


- name: Install regolith-i3 dependencies pt4
  apt:
    name: [libpangocairo-1.0-0,libpango1.0-dev]
    update_cache: yes
  when:
      - ansible_distribution  ["Debian","Ubuntu"]


