---

- name: import tasks from devtools.yml
  import_tasks: devtools.yml
  when:
    - not skip_devtools
  tags:
    - devtools

- name: import tasks from sound.yml
  import_tasks: sound.yml
  when:
    - not skip_sound
  tags:
    - sound

- name: import tasks from user.yml
  import_tasks: user.yml
  when:
    - not skip_user
  tags:
    - user

- name: import tasks from speechd.yml
  import_tasks: speechd.yml
  when:
    - not skip_speechd
  tags:
    - speechd


- name: import tasks from desktop.yml
  import_tasks: desktop.yml
  when:
    - not skip_desktop
  tags:
    - desktop
