---

- name: Debian/Ubuntu, replace /etc/network/interfaces
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution in ["Debian","Ubuntu"]


- name: Debian/Ubuntu, install network-manager
  apt:
    name: network-manager
    status: latest
    update_cache: yes
  when:
    - ansible_distribution in ["Debian","Ubuntu"]


