---

- name: Arch, install espeak-ng
  pacman:
    name: espeak-ng
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"
    - use_espeak_new_generation|default(false)

- name: Arch, install espeak (not espeak-ng)
  pacman:
    name: espeak
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"
    - not use_espeak_new_generation|default(false)

#
# Note, the -ng versions of espeak and libespeak are only available from
# stretch onwards
#

- name: Debian, install espeak-ng and libespeak-ng-dev
  apt:
    name: espeak-ng,libespeak-ng-dev
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
    - use_espeak_new_generation|default(false)

- name: Debian, install espeak and libespeak-dev (not ng)
  apt:
    name: espeak,libespeak-dev
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Debian"
    - not use_espeak_new_generation|default(false)

