---

- name: Arch, install espeak (not espeak-ng)
  pacman:
    name: espeak
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"


- name: Debian/Ubuntu, install espeak and libespeak-dev (not ng)
  apt:
    name: espeak,libespeak-dev
    state: latest
    update_cache: yes
  when:
    - ansible_distribution in ["Debian","Ubuntu"]


