---

- name: Arch, install espeak-ng
  pacman:
    name: espeak-ng
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"


- name: Debian/Ubuntu, install espeak-ng and libespeak-ng-dev
  apt:
    name: espeak-ng,libespeak-ng-dev
    state: latest
    update_cache: yes
  when:
    - ansible_distribution in ["Debian","Ubuntu"]


