---

- name: Arch, install xinit
  pacman:
    name: xorg-xinit
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Archlinux"

- name: Debian/Ubuntu, install xinit
  apt:
    name: xinit
    state: latest
    update_cache: yes
  when:
    - ansible_distribution in ["Debian","Ubuntu"]

- name: Install .xinitrc template
  template:
    src: xinitrc.j2
    dest: /home/{{ default_user }}/.xinitrc
    backup: yes
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0644

