---

- name: Import tasks from emacs.yml
  import_tasks: emacs.yml
  when:
    - not skip_emacspeak
  tags:
    console

- name: Import tasks from emacspeak.yml
  import_tasks: emacspeak.yml
  when:
    - not skip_emacspeak
  tags:
    - console

