---

- name: Arch, copy README.md template to default user home directory
  template:
    src: README.md.arch.j2
    dest: "/home/{{ default_user }}/README.md"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0644
  when:
    - ansible_distribution == "Archlinux"

- name: Debian, copy README.md template to default user home directory
  template:
    src: README.md.raspbian.j2
    dest: "/home/{{ default_user}}/README.md"
    mode: 0644
  when:
    - ansible_distribution == "Debian"

