---

# user and group
default_user: pi
default_group: pi


# skip variables control which tasks are included
skip_devtools: false
skip_sound: false
skip_user: false
skip_speechd: false
skip_desktop: false
skip_desktop_manager: false
skip_xinit: false
skip_orca: false

# desktop related stuff. 
desktop_manager: lightdm
enable_desktop_manager: false
start_desktop_manager: false

# speech-dispatcher speechd.conf template variables
AudioOutputMethod: libao
DefaultModule: espeak

